apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-demo-app
  namespace: pp-app-dev  
  labels:
    app: nodejs-demo-app
    environment: development
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-demo-app
  template:
    metadata:
      labels:
        app: nodejs-demo-app
        environment: development
    spec:
      containers:
      - name: nodejs-app
        image: PLACEHOLDER_IMAGE  # Will be replaced by Jenkins sed command
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV dev
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-demo-service
  namespace: pp-app-dev  
  labels:
    app: nodejs-demo-app
spec:
  selector:
    app: nodejs-demo-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: NodePort
